### PR TITLE
Run CI Tests on MacOS

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Closing/reopneing to trigger CI

**Comment by inducer** [comment]
Your workflow syntax is broken, and you're missing a bunch of `$` signs.

**Comment by matthiasdiener** [comment]
> Your workflow syntax is broken, 

I'm not sure what is broken, CI isn't running automatically since I'm a first-time contributor:

image


> and you're missing a bunch of `$` signs.

Added them, thanks!

**Comment by matthiasdiener** [comment]
This is ready for review @inducer . Before merging, you'll probably need to adjust the 'Required' CI checks in the settings.

**Pull request merged**
